comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment

coverage:
  round: up
  range: "60...100"

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: module_backend  # this is an identifier that should not be changed
      name: backend  # this is a display name, and can be changed freely
      paths:
        - src-tauri/src/backend/**
    - component_id: module_tests
      name: tests
      paths:
        - src-tauri/src/tests/**

ignore:
  - "**/tests/**"  # ignore all files in the tests folder
  - "**/tests"  # ignore the tests folder itself
  - "src-tauri/src/backend/utils/**"  # ignore all files in the utils folder
  - "src-tauri/src/main.rs" # ignore the main.rs file