[tool.portray]
modules = [
    "Raspirus.backend.file_module",
    "Raspirus.backend.file_scanner_module",
    "Raspirus.backend.hash_api_module",
    "Raspirus.frontend.utility",
    "Raspirus.frontend.pages.ClearPage",
    "Raspirus.frontend.pages.InfoPage",
    "Raspirus.frontend.pages.LoadingPage",
    "Raspirus.frontend.pages.MainPage",
    "Raspirus.frontend.pages.SettingsLogPage",
    "Raspirus.frontend.pages.SettingsPage",
    "Raspirus.frontend.pages.VirusPage"
]