name: raspirus
base: core18
version: 1.1.0
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored signature detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
grade: devel
confinement: strict
apps:
  raspirus:
    command: raspirus
    extensions:
      - gnome-3-34
    desktop: raspirus.desktop
parts:
  dump-binary:
    plugin: dump
    source: target/release
    source-type: local
    stage:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    prime:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    stage-packages:
      - libc6
