name: raspirus
base: core18
version: git
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored signature detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
grade: stable
confinement: strict
architectures:
  - amd64

parts:
    plugin: dump
    source: https://github.com/Raspirus/Raspirus/releases/download/v1.1.0/raspirus_1.1.0_amd64.deb

apps:
  raspirus:
    command: raspirus