name: raspirus
base: core18
version: git
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored signature detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
grade: stable
confinement: strict
architectures:
  - amd64

apps:
  raspirus:
    command: raspirus
    extensions: [gnome-3-34]
    desktop: raspirus.desktop

parts:
  raspirus-app:
    plugin: nil
    source: .
    build-packages:
      - curl
      - wget
      - build-essential
      - libwebkit2gtk-4.0-dev
      - libssl-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev 
      - librsvg2-dev
    override-pull: |
      craftctl default
      ls -ll
      cd ../../../
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      PATH=~/.cargo/bin:${PATH}
      cargo install tauri-cli
      mkdir out
      cargo install --path src-tauri
      ls -ll ${SNAPCRAFT_PROJECT_DIR}
      ls -ll ${SNAPCRAFT_PART_BUILD}
    override-build: |
      craftctl default
      ls -ll
      cd ../../../
      npm i
      PATH=~/.cargo/bin:${PATH}
      cargo tauri build --ci --out-dir $CRAFT_PART_INSTALL --bundles deb
    build-snaps:
    - node/16/stable
    override-stage:
      ls -la ./
      craftctl default
    stage:
      - target/release/bundle/deb/raspirus_1.1.0_amd64/
    prime:
      - target/release/bundle/deb/raspirus_1.1.0_amd64/data/usr/bin/raspirus
      - target/release/bundle/deb/raspirus_1.1.0_amd64/data/usr/share/applications/raspirus.desktop
      - target/release/bundle/deb/raspirus_1.1.0_amd64/data/usr/share/icons/hicolor/**/apps/raspirus.png

  dump-binary:
    after: [raspirus-app]
    plugin: dump
    source: target/release
    source-type: local
    stage:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    prime:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    stage-packages:
      - libc6