name: raspirus
base: core20
version: 2.0.0
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored rules-based detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
grade: stable
confinement: strict
architectures:
  - amd64
  - arm64
  - riscv64

parts:
  raspirus-amd64:
    plugin: dump
    source: https://github.com/Raspirus/Raspirus/releases/download/v$SNAPCRAFT_PROJECT_VERSION/raspirus_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    source-type: deb
    organize:
      usr/bin/raspirus: usr/bin/raspirus-amd64

  raspirus-arm64:
    plugin: dump
    source: https://github.com/Raspirus/Raspirus/releases/download/v$SNAPCRAFT_PROJECT_VERSION/raspirus_$SNAPCRAFT_PROJECT_VERSION-1_arm64.deb
    source-type: deb
    organize:
      usr/bin/raspirus: usr/bin/raspirus-arm64
  
  raspirus-riscv64:
    plugin: dump
    source: https://github.com/Raspirus/Raspirus/releases/download/v$SNAPCRAFT_PROJECT_VERSION/raspirus_$SNAPCRAFT_PROJECT_VERSION_-1_riscv64.deb
    source-type: deb
    organize:
      usr/bin/raspirus: usr/bin/raspirus-riscv64

apps:
  raspirus-amd64:
    command: raspirus-amd64
  raspirus-arm64:
    command: raspirus-arm64
  raspirus-riscv64:
    command: raspirus-riscv64
