name: raspirus
base: core18
version: 1.1.0
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored signature detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
grade: devel
confinement: strict

apps:
  raspirus:
    command: raspirus
    extensions:
      - gnome-3-34
    desktop: raspirus.desktop

parts:
  build-deps:
    plugin: nil
    build-packages:
      - curl
      - nodejs
      - npm
      - libwebkit2gtk-4.0-dev
      - build-essential
      - wget
      - libssl-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
    source: .

  npm-deps:
    plugin: nodejs
    npm-packages:
      - next@latest
      - react@latest
      - react-dom@latest
      - eslint-config-next@latest

  rust-deps:
    plugin: rust
    rust-version: 1.55.0
    source: .

  tauri-install:
    plugin: rust
    source: .
    override-build: |
      cargo install tauri-cli

  tauri-build:
    plugin: rust
    source: .
    override-build: |
      cargo tauri build
    prime:
      - -target
      - '*'
