name: raspirus
base: core18
version: git
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored signature detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
grade: devel
confinement: strict
compression: lzo
architectures:
  - amd64


apps:
  raspirus:
    command: raspirus
    extensions: [gnome-3-34]
    desktop: raspirus.desktop

parts:
  raspirus-app:
    plugin: nil
    source: .
    build-packages:
      - curl
      - wget
      - build-essential
      - libwebkit2gtk-4.0-dev
      - libssl-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev 
      - librsvg2-dev
    override-pull: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      PATH=~/.cargo/bin:${PATH}
      cargo install tauri-cli
      ls -ll ../../../
      ls -ll ${SNAPCRAFT_PART_SRC}
      mkdir ../../../out
      cargo install --path ../../../src-tauri
      nvm install --lts
      npm i
    override-build: |
      ls -ll
      mkdir out
      PATH=~/.cargo/bin:${PATH}
      cargo tauri build --ci
    prime:
      - "*"

  dump-binary:
    after: [raspirus-app]
    plugin: dump
    source: $SNAPCRAFT_PRIME
    source-type: local
    stage:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    prime:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    stage-packages:
      - libc6

