name: raspirus
base: core18
version: 1.1.0
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored signature detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
grade: devel
confinement: strict
apps:
  raspirus:
    command: raspirus
    extensions:
      - gnome-3-34
    desktop: raspirus.desktop
parts:
  build-deps:
    plugin: nil
    build-packages:
      - curl
      - nodejs
      - npm
      - libwebkit2gtk-4.0-dev
      - build-essential
      - wget
      - libssl-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
    source: .

  npm-deps:
    plugin: nodejs
    npm-packages:
      - next@latest
      - react@latest
      - react-dom@latest
      - eslint-config-next@latest
    
  tauri-install:
    plugin: rust
    source: .
    override-build: |
      cargo install tauri-cli
      cargo install --path .\src-tauri\
      cargo tauri build

  dump-binary:
    plugin: dump
    source: target/release
    source-type: local
    stage:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    prime:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    stage-packages:
      - libc6
