name: raspirus
base: core18
version: 1.0.0
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored signature detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
grade: stable
confinement: strict

parts:
  raspirus:
    plugin: dump
    source: https://github.com/Raspirus/Raspirus/releases/download/v1.1.0/Raspirus_x64.app.tar.gz

apps:
  raspirus:
    command: raspirus

