name: raspirus
base: core18
version: git
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored signature detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
grade: devel
confinement: strict
compression: lzo
architectures:
  - amd64


apps:
  raspirus:
    command: raspirus
    extensions: [gnome-3-34]
    desktop: raspirus.desktop

parts:
  raspirus-app:
    plugin: nil
    source: .
    build-packages:
      - curl
      - wget
      - build-essential
      - libwebkit2gtk-4.0-dev
      - libssl-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev 
      - librsvg2-dev
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      PATH=~/.cargo/bin:${PATH}
      cargo install tauri-cli
      ls -ll ${SNAPCRAFT_PROJECT_DIR}
      ls -ll ${SNAPCRAFT_PART_BUILD}
      mkdir ../../../out
      cargo install --path ../../../src-tauri
    override-build: |
      ls -ll
      mkdir out
      npm i
      PATH=~/.cargo/bin:${PATH}
      cargo tauri build --ci
    build-snaps:
    - node/16/stable
    prime:
      - "*"

  dump-binary:
    after: [raspirus-app]
    plugin: dump
    source: $SNAPCRAFT_PRIME
    source-type: local
    stage:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    prime:
      - lib
      - icons
      - raspirus
      - raspirus.desktop
    stage-packages:
      - libc6

