name: raspirus
base: core22
version: 2.2.1
summary: A resource- and human-friendly malware scanner
description: Raspirus is your cost-free, versatile malware scanner. Tailored rules-based detection, comprehensive file scans, and privacy prioritized for swift, reliable protection.
icon: snap/gui/raspirus.svg
grade: stable
confinement: strict
architectures:
    - build-on: [amd64]
    - build-on: [arm64]
    - build-on: [riscv64]

parts:
    raspirus:
        plugin: rust
        source: .
        stage-packages:
            - libssl-dev
        rust-cargo-parameters: [--no-default-features]

apps:
    raspirus:
        command: bin/raspirus
        plugs:
            - home
            - removable-media
            - network
        extensions:
            - gnome
