name: Cross Compiler

on:
  workflow_dispatch:

env:
  VERSION: 1.2.2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            target: aarch64-unknown-linux-gnu
            apt: gcc-aarch64-linux-gnu
            sysroot: /usr/aarch64-linux-gnu/
            pkg_arch: arm64
          - arch: riscv64
            target: riscv64gc-unknown-linux-gnu
            apt: gcc-riscv64-linux-gnu
            sysroot: /usr/riscv64-linux-gnu/
            pkg_arch: riscv64
          # UNSUPPORTED with iced :(
          - arch: armv7
            target: armv7-unknown-linux-gnueabihf
            apt: gcc-arm-linux-gnueabihf
            sysroot: /usr/arm-linux-gnueabihf/
            pkg_arch: armhf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean install Debian packages
        run: sudo apt-get clean && sudo apt-get update && sudo apt-get upgrade -y

      - name: Install cross-compile deps
        uses: ryankurte/action-apt@v0.4.1
        with:
          arch: ${{ matrix.pkg_arch }}
          packages: "libssl-dev:${{ matrix.pkg_arch }}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            build-essential \
            curl \
            libssl-dev \
            ${{ matrix.apt }} \

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Set environment variables
        run: echo "PKG_CONFIG_SYSROOT_DIR=${{ matrix.sysroot }}" >> $GITHUB_ENV

      - name: Install deb packager
        run: cargo install cargo-deb

      - name: Package the build
        env:
          PKG_CONFIG_SYSROOT_DIR: ${{ matrix.sysroot }}
        run: |
            cargo deb --target=${{ matrix.target }}

      - name: Create attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: target/${{ matrix.target }}/debian/*.deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg_arch }}-deb
          path: target/${{ matrix.target }}/debian/*.deb
