name: Choco Auto Update

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
    working-directory: chocolatey/raspirus

jobs:
  update_choco_auto:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Install Chocolatey Automatic Package Updater Module
        run: Install-Module -Name Chocolatey-AU -Force

      - name: Run update script
        id: update
        run: |
          $UpdateOutput = .\update.ps1
          $NupkgPath = (($UpdateOutput.Result | Where-Object {$_ -like '*.nupkg''*'}) -split "'")[1]

          if (-not $NupkgPath) {
              Write-Output "Warning: No .nupkg file path found in update script output."
          }

          Write-Output "NupkgPath=$($NupkgPath)" >> $Env:GITHUB_OUTPUT
          $UpdateStatus = if ($UpdateOutput.Result -match 'No new version found') {'No Update'} else {'Update Available'}
          Write-Output "UpdateStatus=$($UpdateStatus)" >> $Env:GITHUB_OUTPUT

      - name: Debug update outputs
        run: |
          Write-Output "NupkgPath from outputs: ${{ steps.update.outputs.NupkgPath }}"
          Write-Output "UpdateStatus from outputs: ${{ steps.update.outputs.UpdateStatus }}"
          if (-not "${{ steps.update.outputs.NupkgPath }}") {
              Write-Output "Debug: NupkgPath is empty. Investigate the update script output and extraction logic."
          }

      - name: Test install
        run: Test-Package -Install -Nu ${{ steps.update.outputs.NupkgPath }}
#        if: steps.update.outputs.UpdateStatus == 'Update Available'

      - name: Publish to Chocolatey community feed
        run: |
          $Nupkg = '${{ steps.update.outputs.NupkgPath }}'
          $ApiKey = '${{ secrets.CHOCO_KEY }}'
          $ChocoServer = 'https://push.chocolatey.org/'
          choco push $Nupkg --source $ChocoServer --key $ApiKey
        if: steps.update.outputs.UpdateStatus == 'Update Available'

      - name: Commit Updated nuspec
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Choco package update - Raspirus ${{ steps.update.outputs.newversion }}
          file_pattern: '*.nuspec *.ps1'
        if: steps.update.outputs.UpdateStatus == 'Update Available'