name: Docker Image CI

on:
  workflow_dispatch:
env:
  VERSION: 1.2.1
jobs:
  build_docker:
    strategy:
      matrix:
        include:
          - arch: arm64
            triple: aarch64-unknown-linux-gnu
            dir: arm
          - arch: armhf
            triple: armv7-unknown-linux-gnueabihf
            dir: armhf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t raspirus-${{ matrix.dir }} -f ./docker/${{ matrix.dir }}/Dockerfile .

      - name: Create the Docker container
        run: docker create --name raspirus raspirus-${{ matrix.dir }}

      - name: Create output folder
        run: mkdir -p ./output

      - name: List Docker release files
        run: docker exec raspirus ls /usr/app/raspirus/target/${{ matrix.triple }}/release/

      - name: List Docker bundle files
        run: docker exec raspirus ls /usr/app/raspirus/target/${{ matrix.triple }}/release/bundle/

      - name: List Docker deb files
        run: docker exec raspirus ls /usr/app/raspirus/target/${{ matrix.triple }}/release/bundle/deb/

      - name: Copy file from Docker container
        run: docker cp raspirus:/usr/app/raspirus/target/${{ matrix.triple }}/release/bundle/deb/raspirus_${{ env.VERSION }}_${{ matrix.arch }}.deb ./output/

      - name: Collect Docker output
        id: collect_docker_files
        run: echo "files=./output/raspirus_${{ env.VERSION }}_${{ matrix.arch }}.deb" >> $GITHUB_ENV