name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Set up Rust
      - uses: actions-rs/toolchain@v1
      - run: rustup target add x86_64-unknown-linux-gnu

      # Build the documentation
      - run: cargo doc --no-deps --document-private-items --all-features
        working-directory: src-tauri

      # Deploy the documentation to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
