name: Pylint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      uses: gabriel-milan/action-pylint@v1
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # GitHub token
        path: "**/*.py" # Glob pattern for files to lint
        fail: false # Fail the action if pylint errors are found
        pr-message: true # Send a PR message if pylint errors are found
