name: Build snap package

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      # You can now run Snapcraft shell commands
      - name: Use Snapcraft
        run: |
          snapcraft login
          snapcraft
          snapcraft upload raspirus/src-tauri/target/raspirus_1.1.1_amd64.snap
          snapcraft upload raspirus/src-tauri/target/raspirus_1.1.1_arm64.snap
          snapcraft upload raspirus/src-tauri/target/raspirus_1.1.1_armhf.snap
